name: ubts_fyp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.1.0
  email_validator: ^3.0.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.1
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.2
  liquid_pull_to_refresh: ^3.0.1
  location: ^7.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/google_fonts/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#5142f5" 
  android_gravity: center
  fullscreen: true
  android_12:
    color: "#5142f5" 

